FROM node:lts-slim

# Create and change to the build directory.
WORKDIR /api

# Copy local code to the container image.
COPY api .

# Use latest npm.
RUN npm i -g npm

# Install production dependencies.
RUN npm i --quiet

# Run
CMD ["node", "index.js"]