FROM mcr.microsoft.com/playwright:focal

################ Test API ################
# Use latest npm
RUN npm i -g npm

# Test API
WORKDIR /api
COPY api .
RUN npm i
RUN npm test

################ Test web app ################

# Global deps
RUN npm i -g npm zx

WORKDIR /web
COPY web .
RUN npm i
COPY config/test.mjs .

RUN zx test.mjs